# Generated by Django 3.1 on 2020-08-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskinfo',
            options={'ordering': ['-id']},
        ),
    ]
